name: Publish to npm

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install deps
        run: npm ci

      - name: Sync package.json version to tag
        shell: bash
        run: |
          echo "ref_name: $GITHUB_REF_NAME"
          VERSION="${GITHUB_REF_NAME#v}"
          echo "Setting package.json version to: $VERSION"
          npm version "$VERSION" --no-git-tag-version

      - name: Build
        run: npm run build

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
