name: Publish to npm

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install deps
        shell: bash
        run: |
          if [ -f package-lock.json ]; then
            echo "Lockfile found → npm ci"
            npm ci --no-fund --no-audit
          else
            echo "No lockfile → npm install"
            npm install --no-fund --no-audit
          fi

      - name: Sync package.json version to tag
        shell: bash
        run: |
          VERSION="${GITHUB_REF_NAME#v}"
          PKG_VERSION=$(node -p "require('./package.json').version")
          echo "Tag version: $VERSION"
          echo "package.json version: $PKG_VERSION"
          if [ "$PKG_VERSION" != "$VERSION" ]; then
            npm version "$VERSION" --no-git-tag-version
            echo "Updated package.json version to $VERSION"
          else
            echo "package.json already at $VERSION; skipping version bump"
          fi

      - name: Build
        run: npm run build

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
