name: Publish to npm

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Sync version to tag
        run: |
          TAG="${GITHUB_REF_NAME#v}"
          node -e "const fs=require('fs');const p=require('./package.json');if(TAG){p.version=TAG;}fs.writeFileSync('package.json',JSON.stringify(p,null,2));"

      - run: npm ci
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
