name: Publish to npm

on:
  release:
    types: [published]     # run when you publish a GitHub Release
  workflow_dispatch:       # or run manually from the Actions tab

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write      # enables npm provenance (optional)
    steps:
      - uses: actions/checkout@v4
    
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
          # cache: 'npm'   <-- remove this because there's no lockfile
    
      - run: npm install --no-audit --no-fund
      - run: npm run build
    
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
